services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: quick_clinic_dev
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_SOCKET_URL: http://localhost:4000
    restart: always
    depends_on:
      - socket-server

  socket-server:
    build:
      context: .
      dockerfile: socket-server/Dockerfile.dev
    container_name: quick_clinic_socket_server
    ports:
      - "4000:4000"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/socket-server/node_modules
    environment:
      NODE_ENV: development
      PORT: 4000
      SOCKET_PORT: 4000
    restart: always
